In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_pickle("data_statis.df")

In [3]:
df

   seq_size  item_num
0        10      3883

In [4]:
train_df = pd.read_pickle("train_data.df")

In [5]:
len(train_df)

755782

In [7]:
train_df[train_df["next"]==72]

                                                      seq  len_seq  next
15116   [44, 2023, 346, 2610, 534, 2288, 2335, 1783, 1...       10    72
15666   [3483, 3323, 3284, 1128, 2249, 2598, 3077, 123...       10    72
23233   [2716, 918, 3605, 2302, 594, 898, 593, 944, 35...       10    72
24076   [2321, 2105, 1390, 156, 3440, 1444, 2814, 2403...       10    72
28014   [902, 903, 3754, 3188, 3564, 3224, 3820, 3298,...       10    72
...                                                   ...      ...   ...
779484  [649, 1212, 2500, 49, 1248, 865, 607, 2027, 27...       10    72
783592  [2857, 526, 1192, 295, 2018, 1207, 3470, 592, ...       10    72
784375  [3061, 1703, 3363, 3485, 2970, 777, 2395, 3466...       10    72
796211  [1410, 234, 3106, 1486, 2124, 2113, 1392, 589,...       10    72
799414  [1230, 1192, 149, 2397, 1245, 594, 1241, 1961,...       10    72

[170 rows x 3 columns]

In [38]:
train_df[train_df["len_seq"]==10]

                                                     seq  len_seq   next
27906  [550, 1088, 4553, 856, 4911, 519, 1269, 1833, ...       10   2713
4915   [3293, 5010, 3305, 6852, 2271, 389, 6319, 305,...       10    435
31136  [2699, 539, 5102, 4527, 134, 2657, 4859, 815, ...       10    321
23498  [5156, 5088, 2680, 872, 779, 822, 1076, 382, 5...       10   2909
38317  [9103, 13679, 400, 635, 6109, 2024, 899, 493, ...       10   2212
5022   [1269, 1239, 2255, 4473, 868, 5575, 667, 432, ...       10   2544
27169  [550, 843, 1072, 568, 851, 5977, 5347, 2679, 1...       10   8227
8899   [2594, 4182, 2008, 7405, 3463, 8812, 11530, 31...       10   3095
31717  [5327, 539, 3452, 812, 7083, 2956, 5117, 2718,...       10   2631
26743  [5096, 2748, 2174, 3633, 550, 838, 4546, 13093...       10   3292
27590  [2696, 2367, 1771, 897, 2716, 2100, 2093, 1245...       10   2054
182    [1771, 2082, 6204, 5382, 1808, 2063, 5857, 894...       10    700
32398  [1877, 1802, 4236, 1920, 2262, 2600, 1938, 4, ...       10     88
2902   [8210, 1857, 695, 847, 669, 1267, 6881, 1068, ...       10   1777
14383  [5389, 5579, 164, 844, 1282, 2509, 1067, 1084,...       10    817
28180  [10445, 1127, 1233, 3214, 501, 11532, 2563, 82...       10   5657
35515  [444, 928, 375, 7091, 539, 3562, 373, 669, 454...       10   1780
37151  [16420, 3512, 2019, 514, 20306, 10141, 1324, 5...       10   2684
27562  [539, 12016, 5462, 4171, 8259, 2586, 3920, 24,...       10   5837
37975  [676, 7033, 449, 877, 3864, 92, 539, 16420, 21...       10   2463
20885  [868, 3334, 570, 1065, 18253, 724, 1300, 8212,...       10   5109
5975   [2720, 432, 812, 1234, 5069, 239, 1267, 1801, ...       10    807
24248  [714, 812, 2699, 664, 2635, 7505, 2026, 566, 2...       10   2698
11809  [843, 740, 840, 2586, 3322, 8000, 2531, 1248, ...       10    769
24750  [970, 3864, 4553, 2367, 1088, 1313, 1268, 3564...       10   2020
38193  [2758, 11652, 5189, 2304, 17887, 9922, 1764, 2...       10   6013
20905  [1795, 663, 1822, 2646, 5347, 667, 2676, 5171,...       10   4020
5982   [513, 3564, 2725, 2094, 5337, 8332, 6107, 539,...       10   3618
35812  [1233, 1798, 4876, 7444, 2677, 7056, 301, 5337...       10   6787
13761  [2465, 1777, 368, 3564, 34, 4085, 3268, 407, 1...       10  18077
6493   [5163, 874, 7492, 11253, 3388, 153, 877, 642, ...       10    120
2770   [124, 9099, 5986, 1771, 6203, 9080, 9205, 6008...       10    833
37181  [3564, 472, 680, 663, 661, 2023, 1789, 1792, 5...       10   1010
39273  [368, 1055, 7077, 2598, 6826, 8897, 5324, 4546...       10   2677
44717  [12363, 12083, 18657, 1823, 8572, 10573, 2821,...       10  17820

In [33]:
train_df

                                                     seq  len_seq   next
2720   [5060, 38, 5569, 5572, 6339, 798086, 798086, 7...        5   4656
12117  [2442, 798086, 798086, 798086, 798086, 798086,...        1   3626
22877  [3989, 5977, 798086, 798086, 798086, 798086, 7...        2   1086
19924  [11695, 2044, 5995, 798086, 798086, 798086, 79...        3   3186
25508  [15504, 8537, 798086, 798086, 798086, 798086, ...        2   9316
...                                                  ...      ...    ...
27295  [4564, 4564, 798086, 798086, 798086, 798086, 7...        2   1389
15300  [4911, 834, 6927, 3849, 2610, 19075, 325, 7980...        7   7125
25695  [5659, 2453, 2587, 18332, 798086, 798086, 7980...        4  15248
20329  [2031, 2573, 3298, 6202, 3867, 798086, 798086,...        5   2155
16999  [3105, 2054, 798086, 798086, 798086, 798086, 7...        2   5034

[36470 rows x 3 columns]

In [4]:
val_df = pd.read_pickle("val_data.df")

In [5]:
val_df["len_seq"].mean()

9.688368271196804

In [6]:
val_df

                                                      seq  len_seq  next
0       [3952, 3952, 3952, 3952, 3952, 3952, 3952, 395...        1  3734
1       [3734, 3952, 3952, 3952, 3952, 3952, 3952, 395...        1  3872
2       [3734, 3872, 3952, 3952, 3952, 3952, 3952, 395...        2   907
3       [3734, 3872, 907, 3952, 3952, 3952, 3952, 3952...        3   355
4       [3734, 3872, 907, 355, 3952, 3952, 3952, 3952,...        4  3419
...                                                   ...      ...   ...
104657  [1253, 3329, 3094, 3151, 918, 904, 1303, 953, ...       10  2392
104658  [3329, 3094, 3151, 918, 904, 1303, 953, 915, 3...       10   198
104659  [3094, 3151, 918, 904, 1303, 953, 915, 3102, 2...       10  1013
104660  [3151, 918, 904, 1303, 953, 915, 3102, 2392, 1...       10  3858
104661  [918, 904, 1303, 953, 915, 3102, 2392, 198, 10...       10  3712

[104662 rows x 3 columns]

In [6]:
test_df = pd.read_pickle("test_data.df")

In [7]:
test_df

                                                      seq  len_seq  next
0       [3952, 3952, 3952, 3952, 3952, 3952, 3952, 395...        1  3734
1       [3734, 3952, 3952, 3952, 3952, 3952, 3952, 395...        1  3872
2       [3734, 3872, 3952, 3952, 3952, 3952, 3952, 395...        2   907
3       [3734, 3872, 907, 3952, 3952, 3952, 3952, 3952...        3   355
4       [3734, 3872, 907, 355, 3952, 3952, 3952, 3952,...        4  3419
...                                                   ...      ...   ...
196102  [2616, 857, 1220, 3467, 1261, 259, 2761, 1926,...       10  2760
196103  [857, 1220, 3467, 1261, 259, 2761, 1926, 1243,...       10  3184
196104  [1220, 3467, 1261, 259, 2761, 1926, 1243, 3915...       10  3128
196105  [3467, 1261, 259, 2761, 1926, 1243, 3915, 2760...       10  3482
196106  [1261, 259, 2761, 1926, 1243, 3915, 2760, 3184...       10  2495

[196107 rows x 3 columns]

In [9]:
df = pd.read_pickle("Test_data.df")
df

                                                    seq  len_seq  next
0     [317, 2924, 1949, 526, 1220, 1275, 1227, 1192,...       10  1246
1     [3174, 1958, 2960, 2700, 2986, 967, 3175, 2996...       10  3645
2     [17, 2278, 2966, 2604, 2125, 3062, 2121, 2902,...       10  2105
3     [2721, 2274, 1689, 184, 255, 2671, 3695, 3877,...       10  2985
4     [376, 1832, 1607, 2762, 647, 1046, 779, 2272, ...       10  1478
...                                                 ...      ...   ...
1203  [3743, 3862, 3299, 3554, 3561, 3512, 3285, 386...       10  3645
1204  [3453, 3615, 3753, 3315, 3298, 3323, 3578, 374...       10  3914
1205  [1135, 1079, 2787, 1088, 295, 1728, 1254, 2166...       10  3665
1206  [1718, 507, 2290, 456, 1570, 1776, 355, 2317, ...       10  1731
1207  [1261, 259, 2761, 1926, 1243, 3915, 2760, 3184...       10  2495

[1208 rows x 3 columns]

In [16]:
wordvec_df = pd.read_pickle('ans2vec.df')

In [17]:
wordvec_df

,answerID,tokenIDs,wordvec_mean_pool,wordvec_max_pool,wordvec_min_pool
0,0,"[0, 1, 2, 3, 4, 5, 3, 6, 7, 8, 9, 1, 10, 11, 1...","[0.06208852, 0.06855498, -0.71278363, 0.454520...","[5.8598123, 6.578013, 5.0940104, 4.826635, 5.5...","[-5.486022, -6.3200917, -5.168874, -4.84341, -..."
1,1,"[165, 166, 67, 166, 167, 166, 167, 168, 166, 1...","[-1.493118, -0.2772092, -0.61790866, -0.284746...","[4.1914706, 6.578013, 6.523269, 6.147097, 4.78...","[-7.501018, -6.5330496, -7.571341, -9.304291, ..."
2,2,"[14, 616, 14, 617, 618, 16, 619, 620, 166, 621...","[-1.143664, 0.06573972, -1.243685, -0.27936432...","[4.3951406, 6.578013, 4.257984, 6.147097, 5.59...","[-7.049544, -6.3200917, -7.8043456, -7.3428707..."
3,3,"[920, 921, 638, 922, 499, 923, 559, 51, 490, 6...","[-1.1513447, 0.12559831, -0.9761636, -0.133994...","[3.5036533, 5.034428, 2.8975375, 4.090445, 6.3...","[-5.336234, -4.5028677, -4.641753, -3.5832353,..."
4,4,"[942, 943, 194, 188, 944, 490, 766, 945, 946, ...","[-0.81306267, 0.27292734, -0.9018367, -0.40726...","[5.528296, 6.578013, 6.0757713, 4.1873784, 4.6...","[-7.0821805, -6.469577, -7.571341, -7.4948344,..."
...,...,...,...,...,...
554971,554971,"[2515, 35511, 5783, 15292, 250, 2382, 16, 2541...","[-0.5322343, -0.31258783, -1.000159, -0.200469...","[3.4735603, 6.390582, 3.340795, 4.1112294, 3.3...","[-3.6614654, -5.3440385, -6.1183033, -4.450593..."
554972,554972,"[147, 959, 1275, 751, 49853, 14, 8512, 147, 95...","[0.07114679, -0.18006271, -0.7815145, 0.624051...","[5.162566, 3.2332218, 3.7003596, 6.3318157, 4....","[-4.1342506, -6.469577, -3.8338475, -2.3845026..."
554973,554973,"[7767, 231, 206391, 69564, 4470, 1376, 6810, 2...","[0.39502797, -0.5212442, -1.0215194, 0.6089472...","[6.3663464, 6.578013, 2.171616, 4.8480296, 2.8...","[-5.486022, -5.1469097, -7.5148287, -4.258501,..."
554974,554974,"[2425, 55954, 323, 71, 15181, 1127, 7720, 51, ...","[-0.16666754, 0.63002557, -1.0895026, -0.17680...","[3.5787945, 4.691534, 3.7003596, 4.1112294, 4....","[-5.708402, -3.8692455, -3.7950337, -4.9471087..."
554975,554975,"[3560, 613, 70, 16, 8118, 44616, 13197, 140, 1...","[-0.25905293, 0.3713257, -1.1819526, -0.296724...","[3.7064977, 6.578013, 4.2635007, 5.9989347, 3....","[-5.486022, -4.546497, -7.5148287, -7.225222, ..."

In [21]:
wordvec_df[wordvec_df["wordvec_mean_pool"].apply(lambda x:x.shape)!=(64,)]

Empty DataFrame
Columns: [answerID, tokenIDs, wordvec_mean_pool, wordvec_max_pool, wordvec_min_pool]
Index: []

In [26]:
word_vectors = np.stack(wordvec_df["wordvec_mean_pool"])

In [27]:
word_vectors

array([[ 0.06208852,  0.06855498, -0.71278363, ..., -0.73291677,
        -0.84137523, -0.19300705],
       [-1.49311805, -0.27720919, -0.61790866, ..., -1.6839776 ,
        -1.38562024, -1.94348752],
       [-1.143664  ,  0.06573972, -1.24368501, ..., -1.54640961,
        -0.89728069, -1.35294127],
       ...,
       [ 0.39502797, -0.52124423, -1.02151942, ..., -1.91153812,
         0.30498564, -0.8850612 ],
       [-0.16666754,  0.63002557, -1.08950257, ..., -0.50870574,
         0.21590863, -0.48763695],
       [-0.25905293,  0.3713257 , -1.1819526 , ..., -1.41505086,
        -0.27366063, -0.08353067]])

In [22]:
import torch
from torch import nn

In [28]:
embedding_matrix = torch.tensor(word_vectors)

In [39]:
import torch
from torch import nn

In [48]:
np.stack(wordvec_df["answerID"])

array([     0,      1,      2, ..., 554973, 554974, 554975])

In [41]:
state_size = 10
hidden_size = 64
positional_embeddings = nn.Embedding(
        num_embeddings=state_size,
        embedding_dim=hidden_size
)

In [44]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [46]:
positional_embeddings(torch.arange(state_size).to(device))

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper__index_select)

In [49]:
torch.cuda.empty_cache()